// examples/nuxt-chat/app/pages/chat.vue
<script setup lang="ts">
import { type UIMessage, useChat } from "@chat-adapter/web/vue";
import { computed, nextTick, ref, watch } from "vue";

const chat = useChat({ api: "/api/chat", threadId: "demo" });

const input = ref("");
const scrollContainer = ref<HTMLDivElement | null>(null);

const busy = computed(
  () => chat.status === "submitted" || chat.status === "streaming"
);
const lastMessage = computed(() => chat.messages.at(-1));

function textOf(message: UIMessage): string {
  let text = "";
  for (const part of message.parts) {
    if (part.type === "text") {
      text += part.text;
    }
  }
  return text;
}

watch(
  () => [chat.messages.length, chat.status] as const,
  async () => {
    await nextTick();
    scrollContainer.value?.scrollTo({
      top: scrollContainer.value.scrollHeight,
      behavior: "smooth",
    });
  }
);

function onSubmit() {
  const text = input.value.trim();
  if (!text || busy.value) {
    return;
  }
  chat.sendMessage({ text });
  input.value = "";
}

function onKeydown(event: KeyboardEvent) {
  if (event.key === "Enter" && !event.shiftKey) {
    event.preventDefault();
    onSubmit();
  }
}
</script>

<template>
  <main class="chat-page">
    <div ref="scrollContainer" aria-live="polite" class="chat-scroll">
      <div v-if="chat.messages.length === 0 && !busy" class="chat-empty">
        <p>What can I help you with?</p>
      </div>
      <template v-else>
        <div v-for="message in chat.messages" :key="message.id">
          <div v-if="message.role === 'user'" class="chat-bubble-user">
            {{ textOf(message) }}
          </div>
          <div v-else class="chat-bubble-assistant">
            {{ textOf(message)
            }}<span
              v-if="
                message === lastMessage &&
                chat.status === 'streaming' &&
                !textOf(message)
              "
              class="chat-cursor"
            />
          </div>
        </div>
        <div v-if="chat.status === 'submitted'" class="chat-thinking">
          Thinking...
        </div>
      </template>
    </div>

    <div v-if="chat.error" class="chat-error">{{ chat.error.message }}</div>

    <form class="chat-form" @submit.prevent="onSubmit">
      <textarea
        v-model="input"
        aria-label="Message"
        class="chat-input"
        :disabled="busy"
        :placeholder="
          chat.messages.length === 0 ? 'What can I help you with?' : 'Reply...'
        "
        rows="1"
        @keydown="onKeydown"
      />
      <div class="chat-actions">
        <button
          v-if="busy"
          class="chat-stop"
          type="button"
          @click="chat.stop()"
        >
          Stop
        </button>
        <button
          v-else
          class="chat-send"
          :disabled="!input.trim()"
          type="submit"
        >
          Send
        </button>
      </div>
    </form>
  </main>
</template>

// examples/nextjs-chat/src/app/chat/page.tsx
"use client";

import { useChat } from "@chat-adapter/web/react";
import { type FormEvent, useEffect, useRef, useState } from "react";

export default function ChatPage() {
  const { messages, sendMessage, status, stop, error } = useChat();
  const [input, setInput] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);

  const busy = status === "submitted" || status === "streaming";

  // biome-ignore lint/correctness/useExhaustiveDependencies: scroll on new messages and status changes
  useEffect(() => {
    scrollRef.current?.scrollTo({
      top: scrollRef.current.scrollHeight,
      behavior: "smooth",
    });
  }, [messages.length, status]);

  const onSubmit = (event?: FormEvent<HTMLFormElement>) => {
    event?.preventDefault();
    const text = input.trim();
    if (!text || busy) {
      return;
    }
    sendMessage({ text });
    setInput("");
  };

  const onKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      onSubmit();
    }
  };

  return (
    <main className="mx-auto flex h-screen max-w-2xl flex-col px-4">
      <div
        aria-live="polite"
        className="hide-scrollbar flex-1 space-y-5 overflow-y-auto pt-12 pb-4"
        ref={scrollRef}
      >
        {messages.length === 0 && !busy ? (
          <div className="flex h-full items-center justify-center">
            <p className="text-sm" style={{ color: "var(--muted-foreground)" }}>
              What can I help you with?
            </p>
          </div>
        ) : (
          <>
            {messages.map((message) => {
              const text = message.parts
                .filter((part) => part.type === "text")
                .map((part) => (part as { text: string }).text)
                .join("");
              const isUser = message.role === "user";
              const isLastAssistant = !isUser && message === messages.at(-1);
              const isStreaming = isLastAssistant && status === "streaming";

              return (
                <div key={message.id}>
                  {isUser ? (
                    <div
                      className="rounded-lg px-3.5 py-3 text-sm"
                      style={{ background: "var(--muted)", opacity: 0.8 }}
                    >
                      {text}
                    </div>
                  ) : (
                    <div
                      className="whitespace-pre-wrap py-2 text-sm leading-relaxed"
                      style={{ color: "var(--foreground)" }}
                    >
                      {text}
                      {isStreaming && !text && (
                        <span
                          className="inline-block h-4 w-0.5"
                          style={{
                            background: "var(--muted-foreground)",
                            animation: "blink 1s ease-in-out infinite",
                          }}
                        />
                      )}
                    </div>
                  )}
                </div>
              );
            })}

            {status === "submitted" && (
              <div
                className="py-2 text-sm"
                style={{
                  color: "var(--muted-foreground)",
                  animation: "breathe 2s ease-in-out infinite",
                }}
              >
                Thinking...
              </div>
            )}
          </>
        )}
      </div>

      {error && (
        <div
          className="mb-3 rounded-lg px-3.5 py-2.5 text-sm"
          style={{
            background: "rgba(239, 68, 68, 0.08)",
            color: "#f87171",
            border: "1px solid rgba(239, 68, 68, 0.15)",
          }}
        >
          {error.message}
        </div>
      )}

      <div className="pt-2 pb-6">
        <form
          className="relative overflow-hidden rounded-xl"
          onSubmit={onSubmit}
          style={{
            background: "var(--muted)",
            border: "1px solid var(--border)",
          }}
        >
          <textarea
            aria-label="Message"
            className="w-full resize-none bg-transparent px-3.5 pt-3.5 pb-12 text-sm outline-none disabled:opacity-50"
            disabled={busy}
            onChange={(event) => setInput(event.target.value)}
            onKeyDown={onKeyDown}
            placeholder={
              messages.length === 0 ? "What can I help you with?" : "Reply..."
            }
            rows={1}
            style={{
              color: "var(--foreground)",
              minHeight: messages.length === 0 ? "120px" : "56px",
              maxHeight: "200px",
            }}
            value={input}
          />
          <div className="absolute right-3 bottom-3 flex items-center gap-2">
            {busy ? (
              <button
                className="rounded-lg px-3 py-1.5 text-xs transition-colors hover:opacity-80"
                onClick={() => stop()}
                style={{
                  background: "var(--border)",
                  color: "var(--muted-foreground)",
                }}
                type="button"
              >
                Stop
              </button>
            ) : (
              <button
                className="rounded-lg px-3 py-1.5 font-medium text-xs transition-opacity disabled:opacity-30"
                disabled={!input.trim()}
                style={{
                  background: "var(--foreground)",
                  color: "var(--background)",
                }}
                type="submit"
              >
                Send
              </button>
            )}
          </div>
        </form>
      </div>
    </main>
  );
}
